apiVersion: v1
kind: Namespace
metadata:
  name: PLACEHOLDER_NAMESPACE
  labels:
    name: PLACEHOLDER_NAMESPACE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-main-data
  namespace: PLACEHOLDER_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: premium-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
  namespace: PLACEHOLDER_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-main
  template:
    metadata:
      labels:
        app: n8n-main
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: n8n
        image: n8nio/n8n:2.1.4
        ports:
        - containerPort: 5678
        env:
        # Basic Configuration
        - name: N8N_USER_FOLDER
          value: "/data"
        - name: N8N_ENCRYPTION_KEY
          value: "PLACEHOLDER_ENCRYPTION_KEY"
        - name: GENERIC_TIMEZONE
          value: "UTC"
        - name: NODE_ENV
          value: "production"
        - name: N8N_EDITOR_BASE_URL
          value: "PLACEHOLDER_BASE_URL"
        - name: WEBHOOK_URL
          value: "PLACEHOLDER_BASE_URL"

        # Database Configuration
        - name: DB_TYPE
          value: "sqlite"
        - name: DB_SQLITE_DATABASE
          value: "/data/database.sqlite"

        # Executions & Logging
        - name: EXECUTIONS_DATA_MAX_AGE
          value: "168"
        - name: N8N_LOG_LEVEL
          value: "warn"

        # Task Runners Configuration
        - name: N8N_RUNNERS_ENABLED
          value: "true"
        - name: N8N_RUNNERS_MODE
          value: "external"
        - name: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: N8N_RUNNERS_AUTH_TOKEN
          value: "PLACEHOLDER_ENCRYPTION_KEY"
        - name: N8N_NATIVE_PYTHON_RUNNER
          value: "true"

        # Security Configuration
        - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
          value: "true"
        - name: NODES_EXCLUDE
          value: "n8n-nodes-base.executeCommand,n8n-nodes-base.localFileTrigger"

        volumeMounts:
        - name: n8n-data
          mountPath: /data
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz/readiness
            port: 5678
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 256m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
      - name: task-runner
        image: n8nio/runners:2.1.4
        env:
        - name: N8N_RUNNERS_TASK_BROKER_URI
          value: "http://localhost:5679"
        - name: N8N_RUNNERS_AUTH_TOKEN
          value: "PLACEHOLDER_ENCRYPTION_KEY"
        # JavaScript Task Runner - Allowed Modules
        - name: NODE_FUNCTION_ALLOW_BUILTIN
          value: "crypto,url,util,querystring,zlib,buffer,string_decoder,stream,events,assert,punycode,timers,console,perf_hooks"
        - name: NODE_FUNCTION_ALLOW_EXTERNAL
          value: "axios,lodash,moment,date-fns,uuid,jsonwebtoken,nanoid,validator,cheerio"
        # Python Task Runner - Allowed Modules
        - name: N8N_RUNNERS_STDLIB_ALLOW
          value: "json,datetime,re,math,random,base64,hashlib,hmac,urllib,uuid,collections,itertools,functools,operator,string,decimal,fractions,statistics,enum,dataclasses,typing"
        - name: GENERIC_TIMEZONE
          value: "UTC"
        resources:
          requests:
            cpu: 128m
            memory: 256Mi
          limits:
            cpu: 256m
            memory: 512Mi
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-main-data
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-main
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: n8n-main
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5678
