apiVersion: v1
kind: Namespace
metadata:
  name: PLACEHOLDER_NAMESPACE
  labels:
    name: PLACEHOLDER_NAMESPACE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-main-data
  namespace: PLACEHOLDER_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
  namespace: PLACEHOLDER_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-main
  template:
    metadata:
      labels:
        app: n8n-main
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: "gen2"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: n8n
        image: n8nio/n8n:2.0.3
        ports:
        - containerPort: 5678
        - containerPort: 5679
        env:
        - name: N8N_USER_FOLDER
          value: "/data"
        - name: N8N_ENCRYPTION_KEY
          value: "PLACEHOLDER_ENCRYPTION_KEY"
        - name: GENERIC_TIMEZONE
          value: "UTC"
        - name: NODE_ENV
          value: "production"
        - name: N8N_EDITOR_BASE_URL
          value: "PLACEHOLDER_BASE_URL"
        - name: DB_TYPE
          value: "sqlite"
        - name: DB_SQLITE_DATABASE
          value: "/data/database.sqlite"
        - name: DB_SQLITE_VACUUM_ON_STARTUP
          value: "true"
        - name: EXECUTIONS_DATA_MAX_AGE
          value: "168"
        - name: N8N_LOG_LEVEL
          value: "warn"
        - name: NODE_FUNCTION_ALLOW_BUILTIN
          value: "*"
        - name: N8N_RUNNERS_ENABLED
          value: "true"
        - name: N8N_RUNNERS_MODE
          value: "external"
        - name: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: N8N_RUNNERS_BROKER_PORT
          value: "5679"
        - name: N8N_RUNNERS_AUTH_TOKEN
          value: "PLACEHOLDER_ENCRYPTION_KEY"
        volumeMounts:
        - name: n8n-data
          mountPath: /data
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - name: task-runner
        image: n8nio/runners:2.0.3
        env:
        - name: N8N_RUNNERS_TASK_BROKER_URI
          value: "http://localhost:5679"
        - name: N8N_RUNNERS_AUTH_TOKEN
          value: "PLACEHOLDER_ENCRYPTION_KEY"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-main-data
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-main
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: n8n-main
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5678
