// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deployments.sql

package db

import (
	"context"
	"encoding/json"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (instance_id, operation, details)
VALUES ($1, $2, $3)
RETURNING id, instance_id, operation, status, details, error_message, started_at, completed_at
`

type CreateDeploymentParams struct {
	InstanceID int32           `json:"instance_id"`
	Operation  string          `json:"operation"`
	Details    json.RawMessage `json:"details"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment, arg.InstanceID, arg.Operation, arg.Details)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Operation,
		&i.Status,
		&i.Details,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getActiveDeployments = `-- name: GetActiveDeployments :many
SELECT id, instance_id, operation, status, details, error_message, started_at, completed_at FROM deployments 
WHERE status IN ('pending', 'running')
ORDER BY started_at ASC
`

func (q *Queries) GetActiveDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, getActiveDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Operation,
			&i.Status,
			&i.Details,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, instance_id, operation, status, details, error_message, started_at, completed_at FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id int32) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Operation,
		&i.Status,
		&i.Details,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listDeploymentsByInstance = `-- name: ListDeploymentsByInstance :many
SELECT id, instance_id, operation, status, details, error_message, started_at, completed_at FROM deployments 
WHERE instance_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListDeploymentsByInstanceParams struct {
	InstanceID int32 `json:"instance_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListDeploymentsByInstance(ctx context.Context, arg ListDeploymentsByInstanceParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByInstance, arg.InstanceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Operation,
			&i.Status,
			&i.Details,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentCompleted = `-- name: UpdateDeploymentCompleted :one
UPDATE deployments 
SET status = 'completed', completed_at = NOW()
WHERE id = $1
RETURNING id, instance_id, operation, status, details, error_message, started_at, completed_at
`

func (q *Queries) UpdateDeploymentCompleted(ctx context.Context, id int32) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, updateDeploymentCompleted, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Operation,
		&i.Status,
		&i.Details,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateDeploymentFailed = `-- name: UpdateDeploymentFailed :one
UPDATE deployments 
SET status = 'failed', error_message = $2, completed_at = NOW()
WHERE id = $1
RETURNING id, instance_id, operation, status, details, error_message, started_at, completed_at
`

type UpdateDeploymentFailedParams struct {
	ID           int32  `json:"id"`
	ErrorMessage string `json:"error_message"`
}

func (q *Queries) UpdateDeploymentFailed(ctx context.Context, arg UpdateDeploymentFailedParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, updateDeploymentFailed, arg.ID, arg.ErrorMessage)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Operation,
		&i.Status,
		&i.Details,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments 
SET status = $2, error_message = $3, completed_at = NOW()
WHERE id = $1
RETURNING id, instance_id, operation, status, details, error_message, started_at, completed_at
`

type UpdateDeploymentStatusParams struct {
	ID           int32  `json:"id"`
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, updateDeploymentStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Operation,
		&i.Status,
		&i.Details,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
