// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: instances.sql

package db

import (
	"context"
)

const checkNamespaceExists = `-- name: CheckNamespaceExists :one
SELECT EXISTS(SELECT 1 FROM instances WHERE namespace = $1 AND deleted_at IS NULL)
`

func (q *Queries) CheckNamespaceExists(ctx context.Context, namespace string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkNamespaceExists, namespace)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (
    user_id, gke_cluster_name, gke_project_id, gke_zone,
    namespace, domain
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, created_at, updated_at, deployed_at, deleted_at
`

type CreateInstanceParams struct {
	UserID         string `json:"user_id"`
	GkeClusterName string `json:"gke_cluster_name"`
	GkeProjectID   string `json:"gke_project_id"`
	GkeZone        string `json:"gke_zone"`
	Namespace      string `json:"namespace"`
	Domain         string `json:"domain"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, createInstance,
		arg.UserID,
		arg.GkeClusterName,
		arg.GkeProjectID,
		arg.GkeZone,
		arg.Namespace,
		arg.Domain,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances WHERE id = $1
`

func (q *Queries) DeleteInstance(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, id)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT id, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, created_at, updated_at, deployed_at, deleted_at FROM instances WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstance(ctx context.Context, id int32) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstanceByNamespace = `-- name: GetInstanceByNamespace :one
SELECT id, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, created_at, updated_at, deployed_at, deleted_at FROM instances WHERE namespace = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstanceByNamespace(ctx context.Context, namespace string) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstanceByNamespace, namespace)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllInstances = `-- name: ListAllInstances :many
SELECT id, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, created_at, updated_at, deployed_at, deleted_at FROM instances 
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllInstancesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllInstances(ctx context.Context, arg ListAllInstancesParams) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, listAllInstances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.GkeClusterName,
			&i.GkeProjectID,
			&i.GkeZone,
			&i.Namespace,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeployedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesByUser = `-- name: ListInstancesByUser :many
SELECT id, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, created_at, updated_at, deployed_at, deleted_at FROM instances 
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInstancesByUser(ctx context.Context, userID string) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, listInstancesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.GkeClusterName,
			&i.GkeProjectID,
			&i.GkeZone,
			&i.Namespace,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeployedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInstance = `-- name: SoftDeleteInstance :one
UPDATE instances 
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, created_at, updated_at, deployed_at, deleted_at
`

func (q *Queries) SoftDeleteInstance(ctx context.Context, id int32) (Instance, error) {
	row := q.db.QueryRowContext(ctx, softDeleteInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInstanceDeployed = `-- name: UpdateInstanceDeployed :one
UPDATE instances 
SET status = $2, deployed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, created_at, updated_at, deployed_at, deleted_at
`

type UpdateInstanceDeployedParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInstanceDeployed(ctx context.Context, arg UpdateInstanceDeployedParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, updateInstanceDeployed, arg.ID, arg.Status)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInstanceNamespace = `-- name: UpdateInstanceNamespace :one
UPDATE instances 
SET namespace = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, created_at, updated_at, deployed_at, deleted_at
`

type UpdateInstanceNamespaceParams struct {
	ID        int32  `json:"id"`
	Namespace string `json:"namespace"`
}

func (q *Queries) UpdateInstanceNamespace(ctx context.Context, arg UpdateInstanceNamespaceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, updateInstanceNamespace, arg.ID, arg.Namespace)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :one
UPDATE instances 
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, created_at, updated_at, deployed_at, deleted_at
`

type UpdateInstanceStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, updateInstanceStatus, arg.ID, arg.Status)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}
