// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: instances.sql

package db

import (
	"context"
)

const checkNamespaceExists = `-- name: CheckNamespaceExists :one
SELECT EXISTS(SELECT 1 FROM instances WHERE namespace = $1 AND deleted_at IS NULL)
`

func (q *Queries) CheckNamespaceExists(ctx context.Context, namespace string) (bool, error) {
	row := q.db.QueryRow(ctx, checkNamespaceExists, namespace)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSubdomainExists = `-- name: CheckSubdomainExists :one
SELECT EXISTS(SELECT 1 FROM instances WHERE subdomain = $1 AND deleted_at IS NULL)
`

func (q *Queries) CheckSubdomainExists(ctx context.Context, subdomain string) (bool, error) {
	row := q.db.QueryRow(ctx, checkSubdomainExists, subdomain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveInstancesByUserID = `-- name: CountActiveInstancesByUserID :one
SELECT COUNT(*) FROM instances WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountActiveInstancesByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveInstancesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (
    user_id, namespace, subdomain, status, app_version
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version
`

type CreateInstanceParams struct {
	UserID     string `json:"user_id"`
	Namespace  string `json:"namespace"`
	Subdomain  string `json:"subdomain"`
	Status     string `json:"status"`
	AppVersion string `json:"app_version"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.UserID,
		arg.Namespace,
		arg.Subdomain,
		arg.Status,
		arg.AppVersion,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Namespace,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
		&i.AppVersion,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
UPDATE instances 
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version
`

func (q *Queries) DeleteInstance(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteInstance, id)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version FROM instances WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstance(ctx context.Context, id string) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Namespace,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
		&i.AppVersion,
	)
	return i, err
}

const getInstanceByNamespace = `-- name: GetInstanceByNamespace :one
SELECT id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version FROM instances WHERE namespace = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstanceByNamespace(ctx context.Context, namespace string) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceByNamespace, namespace)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Namespace,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
		&i.AppVersion,
	)
	return i, err
}

const getInstanceBySubdomain = `-- name: GetInstanceBySubdomain :one
SELECT id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version FROM instances WHERE subdomain = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstanceBySubdomain(ctx context.Context, subdomain string) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceBySubdomain, subdomain)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Namespace,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
		&i.AppVersion,
	)
	return i, err
}

const getInstanceForUpdate = `-- name: GetInstanceForUpdate :one
SELECT id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version FROM instances WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GetInstanceForUpdate(ctx context.Context, id string) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceForUpdate, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Namespace,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
		&i.AppVersion,
	)
	return i, err
}

const listAllInstances = `-- name: ListAllInstances :many
SELECT id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version FROM instances 
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllInstancesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllInstances(ctx context.Context, arg ListAllInstancesParams) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listAllInstances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Namespace,
			&i.Subdomain,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeployedAt,
			&i.DeletedAt,
			&i.AppVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesByUser = `-- name: ListInstancesByUser :many
SELECT id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version FROM instances 
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInstancesByUser(ctx context.Context, userID string) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listInstancesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Namespace,
			&i.Subdomain,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeployedAt,
			&i.DeletedAt,
			&i.AppVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstanceDeployed = `-- name: UpdateInstanceDeployed :one
UPDATE instances 
SET status = $2, deployed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version
`

type UpdateInstanceDeployedParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInstanceDeployed(ctx context.Context, arg UpdateInstanceDeployedParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstanceDeployed, arg.ID, arg.Status)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Namespace,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
		&i.AppVersion,
	)
	return i, err
}

const updateInstanceNamespace = `-- name: UpdateInstanceNamespace :one
UPDATE instances 
SET namespace = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version
`

type UpdateInstanceNamespaceParams struct {
	ID        string `json:"id"`
	Namespace string `json:"namespace"`
}

func (q *Queries) UpdateInstanceNamespace(ctx context.Context, arg UpdateInstanceNamespaceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstanceNamespace, arg.ID, arg.Namespace)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Namespace,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
		&i.AppVersion,
	)
	return i, err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :one
UPDATE instances 
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, namespace, subdomain, created_at, updated_at, deployed_at, deleted_at, app_version
`

type UpdateInstanceStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstanceStatus, arg.ID, arg.Status)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Namespace,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
		&i.AppVersion,
	)
	return i, err
}
