// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: instances.sql

package db

import (
	"context"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (
    name, user_id, gke_cluster_name, gke_project_id, gke_zone,
    namespace, domain, worker_replicas, main_cpu_request, main_memory_request,
    worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, name, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, worker_replicas, main_cpu_request, main_memory_request, worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size, created_at, updated_at, deployed_at, deleted_at
`

type CreateInstanceParams struct {
	Name                string `json:"name"`
	UserID              string `json:"user_id"`
	GkeClusterName      string `json:"gke_cluster_name"`
	GkeProjectID        string `json:"gke_project_id"`
	GkeZone             string `json:"gke_zone"`
	Namespace           string `json:"namespace"`
	Domain              string `json:"domain"`
	WorkerReplicas      int32  `json:"worker_replicas"`
	MainCpuRequest      string `json:"main_cpu_request"`
	MainMemoryRequest   string `json:"main_memory_request"`
	WorkerCpuRequest    string `json:"worker_cpu_request"`
	WorkerMemoryRequest string `json:"worker_memory_request"`
	PostgresStorageSize string `json:"postgres_storage_size"`
	N8nStorageSize      string `json:"n8n_storage_size"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, createInstance,
		arg.Name,
		arg.UserID,
		arg.GkeClusterName,
		arg.GkeProjectID,
		arg.GkeZone,
		arg.Namespace,
		arg.Domain,
		arg.WorkerReplicas,
		arg.MainCpuRequest,
		arg.MainMemoryRequest,
		arg.WorkerCpuRequest,
		arg.WorkerMemoryRequest,
		arg.PostgresStorageSize,
		arg.N8nStorageSize,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.WorkerReplicas,
		&i.MainCpuRequest,
		&i.MainMemoryRequest,
		&i.WorkerCpuRequest,
		&i.WorkerMemoryRequest,
		&i.PostgresStorageSize,
		&i.N8nStorageSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances WHERE id = $1
`

func (q *Queries) DeleteInstance(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, id)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT id, name, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, worker_replicas, main_cpu_request, main_memory_request, worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size, created_at, updated_at, deployed_at, deleted_at FROM instances WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstance(ctx context.Context, id int32) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.WorkerReplicas,
		&i.MainCpuRequest,
		&i.MainMemoryRequest,
		&i.WorkerCpuRequest,
		&i.WorkerMemoryRequest,
		&i.PostgresStorageSize,
		&i.N8nStorageSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstanceByName = `-- name: GetInstanceByName :one
SELECT id, name, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, worker_replicas, main_cpu_request, main_memory_request, worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size, created_at, updated_at, deployed_at, deleted_at FROM instances WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstanceByName(ctx context.Context, name string) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstanceByName, name)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.WorkerReplicas,
		&i.MainCpuRequest,
		&i.MainMemoryRequest,
		&i.WorkerCpuRequest,
		&i.WorkerMemoryRequest,
		&i.PostgresStorageSize,
		&i.N8nStorageSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllInstances = `-- name: ListAllInstances :many
SELECT id, name, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, worker_replicas, main_cpu_request, main_memory_request, worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size, created_at, updated_at, deployed_at, deleted_at FROM instances 
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllInstancesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllInstances(ctx context.Context, arg ListAllInstancesParams) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, listAllInstances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Status,
			&i.GkeClusterName,
			&i.GkeProjectID,
			&i.GkeZone,
			&i.Namespace,
			&i.Domain,
			&i.WorkerReplicas,
			&i.MainCpuRequest,
			&i.MainMemoryRequest,
			&i.WorkerCpuRequest,
			&i.WorkerMemoryRequest,
			&i.PostgresStorageSize,
			&i.N8nStorageSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeployedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesByUser = `-- name: ListInstancesByUser :many
SELECT id, name, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, worker_replicas, main_cpu_request, main_memory_request, worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size, created_at, updated_at, deployed_at, deleted_at FROM instances 
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInstancesByUser(ctx context.Context, userID string) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, listInstancesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Status,
			&i.GkeClusterName,
			&i.GkeProjectID,
			&i.GkeZone,
			&i.Namespace,
			&i.Domain,
			&i.WorkerReplicas,
			&i.MainCpuRequest,
			&i.MainMemoryRequest,
			&i.WorkerCpuRequest,
			&i.WorkerMemoryRequest,
			&i.PostgresStorageSize,
			&i.N8nStorageSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeployedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInstance = `-- name: SoftDeleteInstance :one
UPDATE instances 
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, name, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, worker_replicas, main_cpu_request, main_memory_request, worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size, created_at, updated_at, deployed_at, deleted_at
`

func (q *Queries) SoftDeleteInstance(ctx context.Context, id int32) (Instance, error) {
	row := q.db.QueryRowContext(ctx, softDeleteInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.WorkerReplicas,
		&i.MainCpuRequest,
		&i.MainMemoryRequest,
		&i.WorkerCpuRequest,
		&i.WorkerMemoryRequest,
		&i.PostgresStorageSize,
		&i.N8nStorageSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInstanceDeployed = `-- name: UpdateInstanceDeployed :one
UPDATE instances 
SET status = $2, deployed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, name, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, worker_replicas, main_cpu_request, main_memory_request, worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size, created_at, updated_at, deployed_at, deleted_at
`

type UpdateInstanceDeployedParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInstanceDeployed(ctx context.Context, arg UpdateInstanceDeployedParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, updateInstanceDeployed, arg.ID, arg.Status)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.WorkerReplicas,
		&i.MainCpuRequest,
		&i.MainMemoryRequest,
		&i.WorkerCpuRequest,
		&i.WorkerMemoryRequest,
		&i.PostgresStorageSize,
		&i.N8nStorageSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInstanceResources = `-- name: UpdateInstanceResources :one
UPDATE instances 
SET worker_replicas = $2, main_cpu_request = $3, main_memory_request = $4,
    worker_cpu_request = $5, worker_memory_request = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, worker_replicas, main_cpu_request, main_memory_request, worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size, created_at, updated_at, deployed_at, deleted_at
`

type UpdateInstanceResourcesParams struct {
	ID                  int32  `json:"id"`
	WorkerReplicas      int32  `json:"worker_replicas"`
	MainCpuRequest      string `json:"main_cpu_request"`
	MainMemoryRequest   string `json:"main_memory_request"`
	WorkerCpuRequest    string `json:"worker_cpu_request"`
	WorkerMemoryRequest string `json:"worker_memory_request"`
}

func (q *Queries) UpdateInstanceResources(ctx context.Context, arg UpdateInstanceResourcesParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, updateInstanceResources,
		arg.ID,
		arg.WorkerReplicas,
		arg.MainCpuRequest,
		arg.MainMemoryRequest,
		arg.WorkerCpuRequest,
		arg.WorkerMemoryRequest,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.WorkerReplicas,
		&i.MainCpuRequest,
		&i.MainMemoryRequest,
		&i.WorkerCpuRequest,
		&i.WorkerMemoryRequest,
		&i.PostgresStorageSize,
		&i.N8nStorageSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :one
UPDATE instances 
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, user_id, status, gke_cluster_name, gke_project_id, gke_zone, namespace, domain, worker_replicas, main_cpu_request, main_memory_request, worker_cpu_request, worker_memory_request, postgres_storage_size, n8n_storage_size, created_at, updated_at, deployed_at, deleted_at
`

type UpdateInstanceStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, updateInstanceStatus, arg.ID, arg.Status)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Status,
		&i.GkeClusterName,
		&i.GkeProjectID,
		&i.GkeZone,
		&i.Namespace,
		&i.Domain,
		&i.WorkerReplicas,
		&i.MainCpuRequest,
		&i.MainMemoryRequest,
		&i.WorkerCpuRequest,
		&i.WorkerMemoryRequest,
		&i.PostgresStorageSize,
		&i.N8nStorageSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployedAt,
		&i.DeletedAt,
	)
	return i, err
}
