// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckoutSession struct {
	ID          string           `json:"id"`
	UserID      string           `json:"user_id"`
	InstanceID  string           `json:"instance_id"`
	Subdomain   string           `json:"subdomain"`
	UserEmail   string           `json:"user_email"`
	Status      string           `json:"status"`
	SuccessUrl  string           `json:"success_url"`
	ReturnUrl   string           `json:"return_url"`
	CheckoutID  string           `json:"checkout_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type Instance struct {
	ID         string           `json:"id"`
	UserID     string           `json:"user_id"`
	Status     string           `json:"status"`
	Namespace  string           `json:"namespace"`
	Subdomain  string           `json:"subdomain"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeployedAt pgtype.Timestamp `json:"deployed_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type Subscription struct {
	ID             string           `json:"id"`
	UserID         string           `json:"user_id"`
	ProductID      string           `json:"product_id"`
	CustomerID     string           `json:"customer_id"`
	SubscriptionID string           `json:"subscription_id"`
	Status         string           `json:"status"`
	Quantity       int32            `json:"quantity"`
	TrialEndsAt    pgtype.Timestamp `json:"trial_ends_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID          string           `json:"id"`
	Email       string           `json:"email"`
	Name        string           `json:"name"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastLoginAt pgtype.Timestamp `json:"last_login_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
