// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Instance struct {
	ID             string       `json:"id"`
	UserID         string       `json:"user_id"`
	Status         string       `json:"status"`
	GkeClusterName string       `json:"gke_cluster_name"`
	GkeProjectID   string       `json:"gke_project_id"`
	GkeZone        string       `json:"gke_zone"`
	Namespace      string       `json:"namespace"`
	Subdomain      string       `json:"subdomain"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	DeployedAt     sql.NullTime `json:"deployed_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Subscription struct {
	ID                  string       `json:"id"`
	UserID              string       `json:"user_id"`
	PolarProductID      string       `json:"polar_product_id"`
	PolarCustomerID     string       `json:"polar_customer_id"`
	PolarSubscriptionID string       `json:"polar_subscription_id"`
	Seats               int32        `json:"seats"`
	Status              string       `json:"status"`
	TrialEndsAt         sql.NullTime `json:"trial_ends_at"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           time.Time    `json:"updated_at"`
}

type User struct {
	ID          string       `json:"id"`
	Email       string       `json:"email"`
	Name        string       `json:"name"`
	CreatedAt   time.Time    `json:"created_at"`
	LastLoginAt sql.NullTime `json:"last_login_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}
