// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AcquireLock(ctx context.Context, hashtext string) error
	CheckNamespaceExists(ctx context.Context, namespace string) (bool, error)
	CheckSubdomainExists(ctx context.Context, subdomain string) (bool, error)
	CountActiveInstancesByUserID(ctx context.Context, userID string) (int64, error)
	CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error)
	CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteInstance(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, token string) error
	DeleteSubscriptionByID(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	GetCheckoutSessionByID(ctx context.Context, id string) (CheckoutSession, error)
	GetCheckoutSessionByProviderID(ctx context.Context, checkoutID string) (CheckoutSession, error)
	GetInstance(ctx context.Context, id string) (Instance, error)
	GetInstanceByNamespace(ctx context.Context, namespace string) (Instance, error)
	GetInstanceBySubdomain(ctx context.Context, subdomain string) (Instance, error)
	GetInstanceForUpdate(ctx context.Context, id string) (Instance, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetSubscriptionByProviderID(ctx context.Context, subscriptionID string) (Subscription, error)
	GetSubscriptionByUserID(ctx context.Context, userID string) (Subscription, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListAllInstances(ctx context.Context, arg ListAllInstancesParams) ([]Instance, error)
	ListCheckoutSessions(ctx context.Context, limit int32) ([]CheckoutSession, error)
	ListInstancesByUser(ctx context.Context, userID string) ([]Instance, error)
	ReleaseLock(ctx context.Context, hashtext string) error
	UpdateCheckoutSessionCompleted(ctx context.Context, arg UpdateCheckoutSessionCompletedParams) error
	UpdateCheckoutSessionStatus(ctx context.Context, arg UpdateCheckoutSessionStatusParams) error
	UpdateInstanceDeployed(ctx context.Context, arg UpdateInstanceDeployedParams) (Instance, error)
	UpdateInstanceNamespace(ctx context.Context, arg UpdateInstanceNamespaceParams) (Instance, error)
	UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) (Instance, error)
	UpdateSubscriptionByUserID(ctx context.Context, arg UpdateSubscriptionByUserIDParams) error
	UpdateSubscriptionQuantity(ctx context.Context, arg UpdateSubscriptionQuantityParams) error
	UpdateSubscriptionStatusByProviderID(ctx context.Context, arg UpdateSubscriptionStatusByProviderIDParams) error
	UpdateSubscriptionTrialEndsAt(ctx context.Context, arg UpdateSubscriptionTrialEndsAtParams) (Subscription, error)
	UpdateUserLastLogin(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
