// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subscriptions.sql

package db

import (
	"context"
	"database/sql"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    user_id,
    instance_id,
    product_id,
    customer_id,
    subscription_id,
    trial_ends_at,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, instance_id, product_id, customer_id, subscription_id, status, trial_ends_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID         string       `json:"user_id"`
	InstanceID     string       `json:"instance_id"`
	ProductID      string       `json:"product_id"`
	CustomerID     string       `json:"customer_id"`
	SubscriptionID string       `json:"subscription_id"`
	TrialEndsAt    sql.NullTime `json:"trial_ends_at"`
	Status         string       `json:"status"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.UserID,
		arg.InstanceID,
		arg.ProductID,
		arg.CustomerID,
		arg.SubscriptionID,
		arg.TrialEndsAt,
		arg.Status,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstanceID,
		&i.ProductID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriptionByInstanceID = `-- name: DeleteSubscriptionByInstanceID :exec
DELETE FROM subscriptions
WHERE instance_id = $1
`

func (q *Queries) DeleteSubscriptionByInstanceID(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriptionByInstanceID, instanceID)
	return err
}

const getAllSubscriptionsByUserID = `-- name: GetAllSubscriptionsByUserID :many
SELECT id, user_id, instance_id, product_id, customer_id, subscription_id, status, trial_ends_at, created_at, updated_at FROM subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllSubscriptionsByUserID(ctx context.Context, userID string) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, getAllSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstanceID,
			&i.ProductID,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.Status,
			&i.TrialEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByInstanceID = `-- name: GetSubscriptionByInstanceID :one
SELECT id, user_id, instance_id, product_id, customer_id, subscription_id, status, trial_ends_at, created_at, updated_at FROM subscriptions
WHERE instance_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByInstanceID(ctx context.Context, instanceID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByInstanceID, instanceID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstanceID,
		&i.ProductID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByProviderID = `-- name: GetSubscriptionByProviderID :one
SELECT id, user_id, instance_id, product_id, customer_id, subscription_id, status, trial_ends_at, created_at, updated_at FROM subscriptions
WHERE subscription_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByProviderID(ctx context.Context, subscriptionID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByProviderID, subscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstanceID,
		&i.ProductID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByUserIDAndProductID = `-- name: GetSubscriptionByUserIDAndProductID :one
SELECT id, user_id, instance_id, product_id, customer_id, subscription_id, status, trial_ends_at, created_at, updated_at FROM subscriptions
WHERE user_id = $1 AND product_id = $2
LIMIT 1
`

type GetSubscriptionByUserIDAndProductIDParams struct {
	UserID    string `json:"user_id"`
	ProductID string `json:"product_id"`
}

func (q *Queries) GetSubscriptionByUserIDAndProductID(ctx context.Context, arg GetSubscriptionByUserIDAndProductIDParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByUserIDAndProductID, arg.UserID, arg.ProductID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstanceID,
		&i.ProductID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionProviderInfo = `-- name: UpdateSubscriptionProviderInfo :exec
UPDATE subscriptions
SET customer_id = $2,
    subscription_id = $3,
    product_id = $4,
    updated_at = NOW()
WHERE instance_id = $1
`

type UpdateSubscriptionProviderInfoParams struct {
	InstanceID     string `json:"instance_id"`
	CustomerID     string `json:"customer_id"`
	SubscriptionID string `json:"subscription_id"`
	ProductID      string `json:"product_id"`
}

func (q *Queries) UpdateSubscriptionProviderInfo(ctx context.Context, arg UpdateSubscriptionProviderInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionProviderInfo,
		arg.InstanceID,
		arg.CustomerID,
		arg.SubscriptionID,
		arg.ProductID,
	)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET status = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateSubscriptionStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatus, arg.Status, arg.ID)
	return err
}

const updateSubscriptionStatusByProviderID = `-- name: UpdateSubscriptionStatusByProviderID :exec
UPDATE subscriptions
SET status = $2,
    updated_at = NOW()
WHERE subscription_id = $1
`

type UpdateSubscriptionStatusByProviderIDParams struct {
	SubscriptionID string `json:"subscription_id"`
	Status         string `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatusByProviderID(ctx context.Context, arg UpdateSubscriptionStatusByProviderIDParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatusByProviderID, arg.SubscriptionID, arg.Status)
	return err
}

const updateSubscriptionToExpired = `-- name: UpdateSubscriptionToExpired :exec
UPDATE subscriptions
SET status = 'expired',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSubscriptionToExpired(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionToExpired, id)
	return err
}
