// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subscriptions.sql

package db

import (
	"context"
	"database/sql"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    user_id,
    seats,
    polar_product_id,
    polar_customer_id,
    polar_subscription_id,
    trial_ends_at,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, polar_product_id, polar_customer_id, polar_subscription_id, seats, status, trial_ends_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID              string       `json:"user_id"`
	Seats               int32        `json:"seats"`
	PolarProductID      string       `json:"polar_product_id"`
	PolarCustomerID     string       `json:"polar_customer_id"`
	PolarSubscriptionID string       `json:"polar_subscription_id"`
	TrialEndsAt         sql.NullTime `json:"trial_ends_at"`
	Status              string       `json:"status"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.UserID,
		arg.Seats,
		arg.PolarProductID,
		arg.PolarCustomerID,
		arg.PolarSubscriptionID,
		arg.TrialEndsAt,
		arg.Status,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PolarProductID,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.Seats,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementSubscriptionSeats = `-- name: DecrementSubscriptionSeats :exec
UPDATE subscriptions
SET seats = seats - 1,
    updated_at = NOW()
WHERE user_id = $1
AND seats > 0
`

func (q *Queries) DecrementSubscriptionSeats(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, decrementSubscriptionSeats, userID)
	return err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, polar_product_id, polar_customer_id, polar_subscription_id, seats, status, trial_ends_at, created_at, updated_at FROM subscriptions
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PolarProductID,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.Seats,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByUserIDAndProductID = `-- name: GetSubscriptionByUserIDAndProductID :one
SELECT id, user_id, polar_product_id, polar_customer_id, polar_subscription_id, seats, status, trial_ends_at, created_at, updated_at FROM subscriptions
WHERE user_id = $1 AND polar_product_id = $2
LIMIT 1
`

type GetSubscriptionByUserIDAndProductIDParams struct {
	UserID         string `json:"user_id"`
	PolarProductID string `json:"polar_product_id"`
}

func (q *Queries) GetSubscriptionByUserIDAndProductID(ctx context.Context, arg GetSubscriptionByUserIDAndProductIDParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByUserIDAndProductID, arg.UserID, arg.PolarProductID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PolarProductID,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.Seats,
		&i.Status,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSubscriptionSeats = `-- name: IncrementSubscriptionSeats :exec
UPDATE subscriptions
SET seats = seats + 1,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) IncrementSubscriptionSeats(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, incrementSubscriptionSeats, userID)
	return err
}

const incrementSubscriptionSeatsByID = `-- name: IncrementSubscriptionSeatsByID :exec
UPDATE subscriptions
SET seats = seats + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementSubscriptionSeatsByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementSubscriptionSeatsByID, id)
	return err
}

const updateSubscriptionPolarInfo = `-- name: UpdateSubscriptionPolarInfo :exec
UPDATE subscriptions
SET polar_customer_id = $2,
    polar_subscription_id = $3,
    polar_product_id = $4,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateSubscriptionPolarInfoParams struct {
	UserID              string `json:"user_id"`
	PolarCustomerID     string `json:"polar_customer_id"`
	PolarSubscriptionID string `json:"polar_subscription_id"`
	PolarProductID      string `json:"polar_product_id"`
}

func (q *Queries) UpdateSubscriptionPolarInfo(ctx context.Context, arg UpdateSubscriptionPolarInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionPolarInfo,
		arg.UserID,
		arg.PolarCustomerID,
		arg.PolarSubscriptionID,
		arg.PolarProductID,
	)
	return err
}

const updateSubscriptionSeats = `-- name: UpdateSubscriptionSeats :exec
UPDATE subscriptions
SET seats = $2,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateSubscriptionSeatsParams struct {
	UserID string `json:"user_id"`
	Seats  int32  `json:"seats"`
}

func (q *Queries) UpdateSubscriptionSeats(ctx context.Context, arg UpdateSubscriptionSeatsParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionSeats, arg.UserID, arg.Seats)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET status = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateSubscriptionStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatus, arg.Status, arg.ID)
	return err
}

const updateSubscriptionStatusByPolarID = `-- name: UpdateSubscriptionStatusByPolarID :exec
UPDATE subscriptions
SET status = $2,
    updated_at = NOW()
WHERE polar_subscription_id = $1
`

type UpdateSubscriptionStatusByPolarIDParams struct {
	PolarSubscriptionID string `json:"polar_subscription_id"`
	Status              string `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatusByPolarID(ctx context.Context, arg UpdateSubscriptionStatusByPolarIDParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatusByPolarID, arg.PolarSubscriptionID, arg.Status)
	return err
}

const updateSubscriptionToExpired = `-- name: UpdateSubscriptionToExpired :exec
UPDATE subscriptions
SET status = 'expired',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSubscriptionToExpired(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionToExpired, id)
	return err
}
