// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const acquireLock = `-- name: AcquireLock :exec
SELECT pg_advisory_lock(hashtext($1))
`

func (q *Queries) AcquireLock(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, acquireLock, hashtext)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, name
) VALUES (
    $1, $2
) RETURNING id, email, name, created_at, last_login_at, updated_at
`

type CreateUserParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at, last_login_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, created_at, last_login_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseLock = `-- name: ReleaseLock :exec
SELECT pg_advisory_unlock(hashtext($1))
`

func (q *Queries) ReleaseLock(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, releaseLock, hashtext)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :one
UPDATE users 
SET last_login_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, created_at, last_login_at, updated_at
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLastLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}
