// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLock = `-- name: AcquireLock :exec
SELECT pg_advisory_lock(hashtext($1))
`

func (q *Queries) AcquireLock(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, acquireLock, hashtext)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, token, expires_at
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, token, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    string           `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, name
) VALUES (
    $1, $2
) RETURNING id, email, name, created_at, last_login_at, updated_at
`

type CreateUserParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.user_id, s.token, s.expires_at, s.created_at, u.id, u.email, u.name, u.created_at, u.last_login_at, u.updated_at
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = $1 AND s.expires_at > NOW()
`

type GetSessionByTokenRow struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.Token,
		&i.Session.ExpiresAt,
		&i.Session.CreatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.Name,
		&i.User.CreatedAt,
		&i.User.LastLoginAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at, last_login_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, created_at, last_login_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseLock = `-- name: ReleaseLock :exec
SELECT pg_advisory_unlock(hashtext($1))
`

func (q *Queries) ReleaseLock(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, releaseLock, hashtext)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :one
UPDATE users 
SET last_login_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, created_at, last_login_at, updated_at
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLastLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}
